title: <p align="center"> Luis Maldonado</p>

logo: /assets/img/logo.png

description: <p align="center">üèóÔ∏è Structural Engineering </p>
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/luis-maldonado-de-la-torre/">LinkedIn</a> |
  <a href="https://github.com/LuisMaldonadoContributions">GitHub</a>
  </p>
  
  <p align="justify">
  Egresado de la carrera Ingenier√≠a Civil en la Universidad Nacional de Ingenier√≠a. Apasionado con la optimizaci√≥n, An√°lisis S√≠smico, Dise√±o Estructural y la Metodolog√≠a BIM. 
  <br><br>
  Soy asistente de investigacion en el Laboratorio de Dise√±o y Construccion virtual BIM UNI en donde me enfoco en el desarrollo de proyectos de Automatizacion en el √Årea de Ingenier√≠a Estructural. Ademas trabajo en una oficina de Dise√±o Estructural en donde resolvemos los desafios con los ultimos enfoques y tecnologias.
  <br><br>
  </p>

google_analytics: G-ZZYG0XLBM7 
theme: jekyll-theme-minimal