title: <p align="center"> Luis Maldonado</p>

logo: /assets/img/logo.png

description: <p align="center">游끵勇뀹tructural Engineering </p>
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/luis-maldonado-de-la-torre/">LinkedIn</a> |
  <a href="https://github.com/LuisMaldonadoContributions">GitHub</a>
  </p>
  
  <p align="justify">
  Egresado de la carrera Ingenier칤a Civil en la Universidad Nacional de Ingenier칤a. Apasionado con la optimizaci칩n, An치lisis S칤smico, Dise침o Estructural y la metodolog칤a BIM. 
  <br><br>
  Soy asistente de investigacion en el Laboratorio de Dise침o y Construccion virtual BIM UNI en donde me enfoco en el desarrollo de proyectos de Automatizacion en el 츼rea de Ingenier칤a Estructural. Ademas trabajo en una oficina de Dise침o Estructural en donde resolvemos los desafios con los ultimos enfoques y tecnologias.
  <br><br>
  </p>

google_analytics: G-ZZYG0XLBM7  # Google Analytics tracking ID
theme: jekyll-theme-minimal
