title: <p align="center"> Luis Maldonado</p>

logo: /assets/img/logo.png

description: <p align="center">üèóÔ∏è Structural Engineering </p>
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/luis-maldonado-de-la-torre/">LinkedIn</a> |
  <a href="https://github.com/LuisMaldonadoContributions">GitHub</a>
  </p>
  
  <p align="justify">
  Egresado de la carrera de Ingenier√≠a Civil de la Universidad Nacional de Ingenier√≠a. Apasionado con la automatozacion, An√°lisis S√≠smico, Dise√±o Estructural y la Metodolog√≠a BIM-VDC.
  <br><br>
  Spy Asistente de Investigaci√≥n en el Laboratorio de Dise√±o y Construcci√≥n virtual BIM UNI en donde me enfoco en el desarrollo de proyectos de Automatizaci√≥n en el √Årea de Ingenier√≠a Estructural. Adem√°s, trabajo en una oficina de Dise√±o Estructural en donde resolvemos los desaf√≠os actuales con los √∫ltimos enfoques y tecnolog√≠as.
  <br><br>
  </p>

google_analytics: G-ZZYG0XLBM7 
theme: jekyll-theme-minimal